name: Deploy

# 触发工作流执行的场景（合并到publish触发）
on:
  pull_request:
    branches: [deploy]

jobs:
  publish:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout # 检出仓库，检出的是Head分支
        uses: actions/checkout@v3

      - name: 上传项目
        uses: appleboy/scp-action@master
        with:
          # 服务器域名
          host: ${{ secrets.TENCENT_IP }}
          # 服务器用户名
          username: ${{ secrets.TENCENT_USERNAME }}
          # 服务器密码
          password: ${{ secrets.TENCENT_PASSWORD }}
          # 服务器端口
          port: 22
          # 指定上传的文件目录
          source: './dist'
          # 指定上传服务器目录
          target: '/dist'
          # 解压时覆盖现有文件
          overwrite: true
          # 删除指定数量的前导路径元素
          strip_components: 1



