name: Deploy

# 触发工作流执行的场景（合并到publish触发）
on:
  pull_request:
    branches: [deploy]

jobs:
  publish:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3 # 检出仓库，检出的是Head分支
      - uses: pnpm/action-setup@v2 # 设置pnpm
        with:
          version: 8

      - name: Install Dependencies
        run: pnpm i

      - name: Build
        run: |
         pnpm build
         cp -r package.json ./dist
         cp -r Dockerfile ./dist
         cp -r ecosystem.config.cjs ./dist

      - name: Deploy Dist
        uses: cross-the-world/ssh-scp-ssh-pipelines@latest
        with:
          # 服务器域名
          host: ${{ secrets.TENCENT_IP }}
          # 服务器端口
          port: 22
          # 服务器用户名
          user: ${{ secrets.TENCENT_USERNAME }}
          # 服务器密码
          pass: ${{ secrets.TENCENT_PASSWORD }}
          first_ssh: |
            mkdir -p /app 
            rm -rf /app/*
          # 上传服务器目录
          scp: |
           ./dist => /app
          last_ssh: |
            cd /app
            docker stop nest_container || true
            docker rm nest_container || true
            docker build -t nest-image:latest .
            docker run -d --name nest_container -p 3000:3000 nest-image:latest
            





