name: Deploy

# 触发工作流执行的场景（合并到publish触发）
on:
  pull_request:
    branches: [deploy]

jobs:
  publish:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3 # 检出仓库，检出的是Head分支
      - uses: pnpm/action-setup@v2 # 设置pnpm
        with:
          version: 8

      - name: Install Dependencies
        run: pnpm i

      - name: Build
        run: |
         pnpm build
         cp -r package.json ./dist
         cp -r Dockerfile ./dist
         cp -r ecosystem.config.cjs ./dist

      - name: Upload Dist
        uses: dj-256/github-deploy@v1
        with:
          # 服务器域名
          host: ${{ secrets.TENCENT_IP }}
          # 服务器端口
          port: 22
          # 服务器用户名
          username: ${{ secrets.TENCENT_USERNAME }}
          # 服务器密码
          password: ${{ secrets.TENCENT_PASSWORD }}
          # 上传服务器目录
          remote: /app
          local: ./dist




