name: Deploy

# 触发工作流执行的场景（合并到publish触发）
on:
  pull_request:
    branches: [deploy]

jobs:
  publish:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout # 检出仓库，检出的是Head分支
        uses: actions/checkout@v3

      - name: 上传项目
        uses: srueda99/scp-action@v12
        with:
          # 服务器域名 
          host: ${{ secrets.TENCENT_IP }}
          # 服务器端口
          port: 22
          # 服务器用户名
          username: ${{ secrets.TENCENT_USERNAME }}
          # 服务器密码
          password: ${{ secrets.TENCENT_PASSWORD }}
          # 指定上传服务器目录
          destination: '/dist'
          script: |
            # 更新Docker镜像（如果镜像已存在则需要先删除旧镜像）
            cd /dist
            docker build -t nest-image:latest .
            docker stop nest_container || true 
            docker rm nest_container || true
            docker run -d --name nest_container -p 3000:3000 nest-image:latest



